server:
  port: 8010
spring:
  application:
    name: microservice-simple-consumer-movie
#eureka:
#  client:
#    service-url:
#      defaultZone: http://user:password@peer1:8761/eureka/,http://user:password@peer2:8762/eureka/
#  instance:
#    prefer-ip-address: true
#microservice-simple-provider-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
microservice-simple-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001