server:
  port: 8010
spring:
  application:
    name: microservice-simple-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true