server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/ #,http://user:password@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000