server:
  port: 8020
spring:
  application:
    name: microservice-simple-consumer-movie-two
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/ #,http://user:password@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
microservice-simple-provider-user:
  ribbon:
   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com.example.movie.service.UserFeignClient: DEBUG
#feign:
#  hystrix:
#    enabled: false
#microservice-simple-provider-user:
#  ribbon:
#    listOfServers: localhost:8000,localhost:8001