server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/ #,http://user:password@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
#turbine:
#  app-config: microservice-simple-consumer-movie,microservice-simple-consumer-movie-two
#  cluster-name-expression: "'default'"